services:
  postgres:
    image: postgres:18.2-alpine3.23
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: redshark-database
      POSTGRES_USER: redshark-user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U redshark-user -d redshark-database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_volume: